\c :dbname;

\echo 'Topics';
insert into epubtest."Topics"("id", "order", "type") values ($$basic-functionality$$, 1, $$ESSENTIAL$$);
insert into epubtest."Topics"("id", "order", "type") values ($$non-visual-reading$$, 2, $$ESSENTIAL$$);
insert into epubtest."Topics"("id", "order", "type") values ($$visual-adjustments$$, 3, $$ESSENTIAL$$);
insert into epubtest."Topics"("id", "order", "type") values ($$read-aloud$$, 4, $$ESSENTIAL$$);
insert into epubtest."Topics"("id", "order", "type") values ($$media-overlays$$, 5, $$ADVANCED$$);
insert into epubtest."Topics"("id", "order", "type") values ($$math$$, 6, $$ADVANCED$$);
insert into epubtest."Topics"("id", "order", "type") values ($$extended-descriptions$$, 7, $$ADVANCED$$);

\echo 'Langs';
insert into epubtest."Langs"("id", "label") values ($$en$$, $$English$$);
insert into epubtest."Langs"("id", "label") values ($$fr$$, $$Français$$);

\echo 'TestBooks';
insert into epubtest."TestBooks"("id", "epub_id", "topic_id", "lang_id", "version", "title", "description", "ingested", "filename") values (1, $$com.github.epub-testsuite.epub30-test-0301$$, $$basic-functionality$$, $$en$$, $$1.0.0$$, $$Fundamental Accessibility Tests: Basic Functionality$$, $$ These tests include starting the reading system and opening the titles, navigating the content, searching, and using bookmarks and notes.$$, $$2019-01-08 00:00:00+00:00$$, $$Fundamental-Accessibility-Tests-Basic-Functionality-v1.0.0.epub$$);
insert into epubtest."TestBooks"("id", "epub_id", "topic_id", "lang_id", "version", "title", "description", "ingested", "filename") values (2, $$com.github.epub-testsuite.epub30-test-0302$$, $$non-visual-reading$$, $$en$$, $$1.0.0$$, $$Fundamental Accessibility Tests: Non-Visual Reading$$, $$These tests are for evaluating the reading experience with an assistive technology tool such as a screen reader or refreshable Braille display. Tests include continuous reading, pause and resume, reading order, alternative text, table and hyperlink navigation, copying text.$$, $$2019-01-08 00:00:00+00:00$$, $$Fundamental-Accessibility-Tests-Non-Visual-Reading-v1.0.0.epub$$);
insert into epubtest."TestBooks"("id", "epub_id", "topic_id", "lang_id", "version", "title", "description", "ingested", "filename") values (3, $$com.github.epub-testsuite.epub30-test-0303$$, $$visual-adjustments$$, $$en$$, $$1.0.0$$, $$Fundamental Accessibility Tests: Visual Adjustments$$, $$These tests include changing the font and text size, colors, brightness, compatibility with magnification utilities and support for high contrast and SVG images.$$, $$2019-01-08 00:00:00+00:00$$, $$Fundamental-Accessibility-Tests-Visual-Adjustments-v1.0.0.epub$$);
insert into epubtest."TestBooks"("id", "epub_id", "topic_id", "lang_id", "version", "title", "description", "ingested", "filename") values (4, $$com.github.epub-testsuite.epub30-test-0304$$, $$read-aloud$$, $$en$$, $$1.0.0$$, $$Fundamental Accessibility Tests: Read Aloud$$, $$These tests include start, pause and resume Read Aloud, reading order, punctuation support and visual emphasis of the spoken text.$$, $$2019-01-08 00:00:00+00:00$$, $$Fundamental-Accessibility-Tests-Read-Aloud-v1.0.0.epub$$);
insert into epubtest."TestBooks"("id", "epub_id", "topic_id", "lang_id", "version", "title", "description", "ingested", "filename") values (5, $$com.github.epub-testsuite.epub30-test-0320$$, $$media-overlays$$, $$en$$, $$1.0.0$$, $$Advanced Accessibility Tests: Media Overlays$$, $$Accessibility tests for Media Overlays in a reflowable context$$, $$2019-01-08 00:00:00+00:00$$, $$Advanced-Accessibility-Tests-Media-Overlays-v1.0.0.epub$$);
insert into epubtest."TestBooks"("id", "epub_id", "topic_id", "lang_id", "version", "title", "description", "ingested", "filename") values (6, $$com.github.epub-testsuite.epub30-test-0330$$, $$math$$, $$en$$, $$1.0.0$$, $$Advanced Accessibility Tests: Mathematics$$, $$Tests for accessibility strategies for MathML in EPUB$$, $$2019-01-08 00:00:00+00:00$$, $$Advanced-Accessibility-Tests-Mathematics-v1.0.0.epub$$);
insert into epubtest."TestBooks"("id", "epub_id", "topic_id", "lang_id", "version", "title", "description", "ingested", "filename") values (7, $$com.github.epub-testsuite.epub30-test-0340$$, $$extended-descriptions$$, $$en$$, $$1.0.0$$, $$Advanced Accessibility Tests: Extended Descriptions$$, $$Tests for accessible extended descriptions of images in EPUBs$$, $$2019-01-08 00:00:00+00:00$$, $$Advanced-Accessibility-Tests-Extended-Descriptions-v1.0.0.epub$$);

\echo 'Tests';
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Operating system/Platform accessibility$$, $$If you are using a hardware device, it can be started independently and essential accessibility for starting and exiting applications is available.$$, 1, $$TODO XHTML$$, 0, 1, $$file-010$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$The reading system can be activated independently$$, $$If you are using a reading app that requires you to create an online account then the complete getting started process should be accessible.$$, 2, $$TODO XHTML$$, 1, 1, $$file-110$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Open content$$, $$Open the Fundamental Accessibility Test book in the reading system.$$, 3, $$TODO XHTML$$, 2, 1, $$file-210$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Listing documents$$, $$Check if you can navigate inside the bookshelf.$$, 4, $$TODO XHTML$$, 3, 1, $$file-310$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$The table of contents in the app presents the content hierarchy$$, $$Check if the table of Contents is accessible and its hierarchy is presented correctly by the reading system$$, 5, $$TODO XHTML$$, 4, 1, $$nav-005$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Navigate to chapters through the Table of Contents$$, $$Check if you can navigate to a section by using the table of contents.$$, 6, $$TODO XHTML$$, 5, 1, $$nav-010$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Navigate content by pages$$, $$Check if you can navigate the content by pages.$$, 7, $$TODO XHTML$$, 6, 1, $$nav-110$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Navigate forward and backward through reflowed content$$, $$Use any control or command to navigate forward and backwards in the book content.$$, 8, $$TODO XHTML$$, 7, 1, $$nav-210$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Read navigation information$$, $$Use the "Where am I?" or any other similar command available in the reading system and check if you can get information about your current position in the book.$$, 9, $$TODO XHTML$$, 8, 1, $$nav-310$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Perform a search, review the search results$$, $$Perform a search, review the search results and navigate to the selected search result in the content.$$, 10, $$TODO XHTML$$, 9, 1, $$nav-410$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Move across chapters without using TOC$$, $$Check if you can move across chapters without having to use the Table of Contents.$$, 11, $$TODO XHTML$$, 10, 1, $$nav-510$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Add a Bookmark or Highlight$$, $$Some reading systems may have a Highlight feature in place of Bookmarks. The tests for Bookmarks may then be performed with Highlights.$$, 12, $$TODO XHTML$$, 11, 1, $$anno-010$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Review and navigate Bookmarks or Highlights$$, $$Check if you can review and navigate Bookmarks or Highlights.$$, 13, $$TODO XHTML$$, 12, 1, $$anno-110$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Add a note$$, $$Add a Note at this location in the book. Provide a few lines of text in the Note.$$, 14, $$TODO XHTML$$, 13, 1, $$anno-210$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Review and navigate Notes$$, $$Check if you can review and navigate Notes.$$, 15, $$TODO XHTML$$, 14, 1, $$anno-310$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Initiate "read from here"$$, $$Focus on the beginning of a paragraph or a sentence and initiate reading. Reading should continue until interrupted by the user or at the end of the current document, e.g. current chapter. The text being read should preferably remain in view, but this is not a requirement to pass the test.$$, 16, $$TODO XHTML$$, 15, 2, $$reading-010$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Stop and resume reading$$, $$Initiate reading from any point in the book. Stop reading and note the last read position. Initiate reading again and check if reading starts at the last read location. $$, 17, $$TODO XHTML$$, 16, 2, $$reading-110$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$All text should be read in the proper order$$, $$Sample text has been provided to test the reading order. The Paragraph 2 should be read after Paragraph 1. Note that visually Paragraph 2 is placed to the left of Paragraph 1 but it is second in the reading order. $$, 18, $$TODO XHTML$$, 17, 2, $$reading-210$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Image alternate text reading $$, $$Ensure that the alternate text for the image is available. $$, 19, $$TODO XHTML$$, 18, 2, $$reading-310$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Change reading speed$$, $$It should be possible to adjust (increase/decrease) the speed of reading. This test should be performed using the Assistive Technology being used for accessibility evaluation.$$, 20, $$TODO XHTML$$, 19, 2, $$reading-410$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$TTS allows pause for headings, paragraphs, list items, etc$$, $$The user should be able to identify the difference between content items such as headings, paragraphs or list items by sufficient pauses in the TTS reading or appropriate formatting in the Braille device.$$, 21, $$TODO XHTML$$, 20, 2, $$reading-510$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Navigate between the cells, rows and columns in the table$$, $$Check if you can navigate between the rows and columns of the table$$, 22, $$TODO XHTML$$, 21, 2, $$reading-610$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Navigate between internal hyperlinks$$, $$Check if you can navigate between internal hyperlinks.$$, 23, $$TODO XHTML$$, 22, 2, $$reading-710$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Move to the next block item$$, $$Check if you can move to the next available page element e.g. paragraph, image or table by using a common key/gesture like swipe right, down arrow etc.$$, 24, $$TODO XHTML$$, 23, 2, $$reading-810$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Navigate by characters$$, $$Check if it is possible to navigate to next and previous character in the book text by way of any command or gesture.$$, 25, $$TODO XHTML$$, 24, 2, $$reading-910$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Navigate by words$$, $$Check if it is possible to navigate to next and previous word in the book text by way of any command or gesture.$$, 26, $$TODO XHTML$$, 25, 2, $$reading-1010$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Navigate by lines$$, $$Check if it is possible to navigate to next and previous line in the book text by way of any command or gesture.$$, 27, $$TODO XHTML$$, 26, 2, $$reading-1110$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Navigate the content by headings$$, $$Check if you can move to the next and previous headings in this book without using the Table of Contents.$$, 28, $$TODO XHTML$$, 27, 2, $$reading-1210$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Select and copy text$$, $$Reading systems should provide the ability to copy pieces of text that could be used for notes, in quotations, or to facilitate searching terms contained in the book. In some cases, this could be achieved using an AT such as a screen reader, for instance with a dedicated cursor or other procedures. $$, 29, $$TODO XHTML$$, 28, 2, $$reading-1310$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Change font size$$, $$Use the controls available in the application or else in the operating system to change (increase/decrease) the size of the font. The font size change should apply uniformly on all the book content including the Table of Contents, Footnotes, Page List, Notes and Bookmarks.$$, 30, $$TODO XHTML$$, 29, 3, $$visual-010$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Change background and foreground color$$, $$Change background and foreground colour (May be through reading system feature or through OS settings).$$, 31, $$TODO XHTML$$, 30, 3, $$visual-110$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Change brightness$$, $$Use the controls available in the application or else in the operating system to change (increase/decrease) the screen brightness.$$, 32, $$TODO XHTML$$, 31, 3, $$visual-210$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Apply high contrast system configuration$$, $$The reading system interface and book content except images should respect the high contrast mode (invert colors) if present in the Operating System.$$, 33, $$TODO XHTML$$, 32, 3, $$visual-310$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Magnify the User Interface(UI)$$, $$Use the controls available in the application or else in the operating system to magnify the Reading System screen. All aspects of the User Interface such as Menus, Pop-up Windows, Dialog Boxes and Search Box should get magnified uniformly.$$, 34, $$TODO XHTML$$, 33, 3, $$visual-410$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Change Font$$, $$Choose from a selection of fonts, including sans-serif and serif options.$$, 35, $$TODO XHTML$$, 34, 3, $$visual-510$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Support for SVG$$, $$Check if a image is displayed below this paragraph. This image is in SVG format.$$, 36, $$TODO XHTML$$, 35, 3, $$visual-610$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Enlarge SVG image$$, $$Check if the image given in the previous test can be enlarged. $$, 37, $$TODO XHTML$$, 36, 3, $$visual-710$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$The content can be read aloud$$, $$Focus on the beginning of a paragraph or a sentence and initiate reading  with text-to-speech using a feature of the reading system.$$, 38, $$TODO XHTML$$, 37, 4, $$ReadAloud-010$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Stop and resume reading$$, $$Initiate reading from any point in the book. Stop Read Aloud and note the last read position. Initiate reading again using the Read Aloud feature and check if reading starts at the last read location. $$, 39, $$TODO XHTML$$, 38, 4, $$ReadAloud-110$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$The Read Aloud feature should continue until interrupted by the user$$, $$The Read Aloud feature should continue until interrupted by the user, keeping the text being spoken in view.$$, 40, $$TODO XHTML$$, 39, 4, $$ReadAloud-210$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$All text should be read in the proper order$$, $$Sample text has been provided below to test the reading order. The Paragraph 2 should be read after Paragraph 1 by the Read Aloud feature. Note that visually Paragraph 2 is placed to the left of Paragraph 1 but it is second in the reading order. $$, 41, $$TODO XHTML$$, 40, 4, $$ReadAloud-310$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Change Read Aloud reading speed$$, $$It should be possible to adjust (increase/decrease) the speed of reading. $$, 42, $$TODO XHTML$$, 41, 4, $$ReadAloud-410$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Text to Speech handles punctuations and document structure appropriately$$, $$When Read Aloud is activated, there should be slight pauses after headings, list items etc., rather than reading as if it is one continuous section of text.$$, 43, $$TODO XHTML$$, 42, 4, $$ReadAloud-510$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Text is emphasised as it is spoken by read aloud$$, $$Check if the Text is emphasised as it is spoken by read aloud.$$, 44, $$TODO XHTML$$, 43, 4, $$ReadAloud-610$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$The emphasis or highlight colour can be changed$$, $$Activate Read Aloud feature as described in the previous test. Change the colour of emphasis or visual highlight of the text being read aloud using any feature available in the reading system or the operating system. The users should have a choice of different colours for text highlighting.$$, 45, $$TODO XHTML$$, 44, 4, $$ReadAloud-710$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Media Overlays Playback$$, $$Tests whether playback of Media Overlays is supported.$$, 46, $$TODO XHTML$$, 0, 5, $$MOA-BASIC-010$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Pause and resume from the same position, without closing the book $$, $$Tests whether media overlay playback resumes at correct location after pause$$, 47, $$TODO XHTML$$, 1, 5, $$MOA-BASIC-020$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Resume playback from last position on opening a book $$, $$Tests whether playback resumes even when the book is closed and opened again. $$, 48, $$TODO XHTML$$, 2, 5, $$MOA-BASIC-030$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Section Navigation - Previous/Next Phrase$$, $$Tests whether previous/next phrase navigation is supported.$$, 49, $$TODO XHTML$$, 3, 5, $$MOA-NAV-010$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Navigate to previous section $$, $$Tests whether navigation to previous section is supported.$$, 50, $$TODO XHTML$$, 4, 5, $$MOA-NAV-020$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Navigate to next section $$, $$Tests whether navigation to next section is supported.$$, 51, $$TODO XHTML$$, 5, 5, $$MOA-NAV-030$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Navigate with pagelist$$, $$Tests whether navigation to pages is possible using the page list or go to page feature.$$, 52, $$TODO XHTML$$, 6, 5, $$MOA-NAV-040$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Move to next page$$, $$Tests whether navigation to next reflowed page is supported when media overlay is playing.$$, 53, $$TODO XHTML$$, 7, 5, $$MOA-NAV-050$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Move to previous page$$, $$Tests whether navigation to previous reflowed page is supported when media overlay is playing.$$, 54, $$TODO XHTML$$, 8, 5, $$MOA-NAV-060$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Text and media overlay synchronization $$, $$Tests whether media overlay is synchronized with text display. $$, 55, $$TODO XHTML$$, 9, 5, $$MOA-NAV-070$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Set and navigate to bookmarks $$, $$Tests whether bookmarks can be set and navigated to while media overlay is playing. $$, 56, $$TODO XHTML$$, 10, 5, $$MOA-NAV-080$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Section Navigation - TOC $$, $$Tests whether navigation to a new section is supported.$$, 57, $$TODO XHTML$$, 11, 5, $$MOA-NAV-090$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Continuous playback across page turns$$, $$Tests whether Media Overlay playback across page turns is supported.$$, 58, $$TODO XHTML$$, 12, 5, $$MOA-NAV-100$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Support for fallback mechanism$$, $$The test passes if you can see the image and assistive technology the image and reads the following alt-text:"y minus y sub 1, equals, the fraction with numerator y sub 2 minus y sub 1, and denominator x sub 2 minus x sub 1, times open paren x minus x sub 1 close paren"$$, 59, $$TODO XHTML$$, 0, 6, $$math-010$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Support for JavaScript and MathML$$, $$The test passes if the assistive technology reports presence of the MathML expression and provides functionality to read it.$$, 60, $$TODO XHTML$$, 1, 6, $$math-020$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Navigating inline MathML with AT and other technologies$$, $$The test passes if the following steps succeed.The AT or other reading technologies report presence of the MathML expression and provide functionality to read it.If you are a visual user, then please verify that you are able to see the portions of the equation highlighted as you navigate the various parts of the equation.The test fails if you don't read/hear the equation containing an equals sign and the presence of a fraction contained within.$$, 61, $$TODO XHTML$$, 2, 6, $$math-030$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Navigating block MathML with AT and other technologies$$, $$The test passes if the following steps succeed.The AT or other reading technologies report presence of the MathML expression and provide functionality to read it. If you are a visual user, then please verify that you are able to see the portions of the equation highlighted as you navigate the various parts of the equation.The test fails if you don't read/hear the equation containing an equals sign and the presence of a fraction contained within.$$, 62, $$TODO XHTML$$, 3, 6, $$math-040$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Rendering of inline MathML$$, $$The test passes if you are able to visually see the math equation (which should look similar to the reference image of the math equation).The test fails if you are unable to see the MathML-rendered equation or the MathML rendering looks distorted.Note: The equation may look a little different (i.e. not pixel perfect), but the content of the MathML-rendered math equation should be equivalent to the content in the PNG reference image.$$, 63, $$TODO XHTML$$, 4, 6, $$math-050$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Rendering of block MathML$$, $$The test passes if you are able to visually see the math equation (which should look similar to the reference image of the math equation).The test fails if you are unable to see the MathML-rendered equation or the MathML rendering looks distorted.Note: The equation may look a little different (i.e. not pixel perfect), but the content of the MathML-rendered math equation should be equivalent to the content in the PNG reference image.$$, 64, $$TODO XHTML$$, 5, 6, $$math-060$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Detection of aria-details on image (img element) in figure element$$, $$This test passes if aria-details for the image is reported. (For example, your screen reader will announce has details)$$, 65, $$TODO XHTML$$, 0, 7, $$extdesc-010$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Moving to extended description inside figcaption$$, $$This test passes if you can use aria-details to take you to the HTML details/summary element just below the image. (For example your browser or screen reader may provide some shortcut key or an interactive element like button, link etc. for using aria-details.)$$, 66, $$TODO XHTML$$, 1, 7, $$extdesc-020$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Detection and utilization of details and summary elements inside figcaption$$, $$This test passes if all the following steps are successful:$$, 67, $$TODO XHTML$$, 2, 7, $$extdesc-030$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Detection of aria-details$$, $$This test passes if aria-details for the image is reported. (For example, your screen reader will announce has details.)$$, 68, $$TODO XHTML$$, 3, 7, $$extdesc-050$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Moving to extended description next to the image$$, $$This test passes if you can use aria-details to take you to the HTML details/summary element just below the image. (For example your browser or screen reader may provide some shortcut key or an interactive element like button, link etc. for using aria-details.)$$, 69, $$TODO XHTML$$, 4, 7, $$extdesc-060$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Detection and utilization of details and summary elements$$, $$This test passes if all the following steps are successful:$$, 70, $$TODO XHTML$$, 5, 7, $$extdesc-070$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Detection of aria-details on image (img element)$$, $$This test passes if aria-details for the image is reported. (For example, your screen reader will announce has details.)$$, 71, $$TODO XHTML$$, 6, 7, $$extdesc-090$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Linking to extended description at end of chapter$$, $$This test passes if you can use aria-details to take you to the description at the end of the chapter, under the heading "Description of Bar Chart". (For example your browser or screen reader may provide some shortcut key or an interactive element like button, link etc. for using aria-details.)$$, 72, $$TODO XHTML$$, 7, 7, $$extdesc-100$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Fallback technique for linking to extended description via text hyperlink$$, $$This test passes if all the following steps are successful:The link "Follow for extended description" is reported, and on activating, it takes the focus to extended description at end of this document. The extended
          description is placed under the heading "Description of Bar Chart" You can read the extended descriptionOn activating the link "Navigate back to Bar Chart image" below the extended description, it takes the focus back to original position.$$, 73, $$TODO XHTML$$, 8, 7, $$extdesc-110$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Fallback technique for linking to extended description via image hyperlink$$, $$This test passes if all the following steps are successful:The link "Follow link for extended description at end of chapter" is reported, and on activating it takes the focus to extended description at end of this
        document. The extended description is placed under the heading "Description of Peacock"You can read the extended descriptionOn activating the link "Navigate back to Peacock image" below the extended description, it takes the focus back to original position in the image.$$, 74, $$TODO XHTML$$, 9, 7, $$extdesc-120$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$aria-describedby points to an aside in a figcaption$$, $$The test passes if you are able to read/hear the following text when the focus is on the image. (You should be able to read it before reaching the horizontal break):Extended Description Overview
		The chart shows the website hits for the first quarter of 2014. It shows that Site 1 has more visitors than either of the other sites, but the number of visitors is decreasing. Site 2 has a fairly constant number of visitors, while for Site 3 page hits are increasing month on month.
        Note: there may be a lot more text read that is in a table.Note for screen reader users: It is possible that your screen reader reads the text inside aria-describedby before reporting the image. In such a case, please provide your experience in the notes.$$, 75, $$TODO XHTML$$, 10, 7, $$extdesc-150$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$aria-describedby points to an aside at the end of chapter$$, $$The test passes if you are able to read/hear the following text when the focus is on the image. (You should be able to read the description before reaching the Filler simulating aside at the end of the chapter)The male is metallic blue on the crown, the feathers of the head being short and curled. The fan-shaped crest on the head
            is made of feathers with bare black shafts and tipped with blush-green webbing. A white stripe above the eye
            and a crescent shaped white patch below the eye are formed by bare white skin. The sides of the head have iridescent
            greenish blue feathers. The back has scaly bronze-green feathers with black and copper markings."$$, 76, $$TODO XHTML$$, 11, 7, $$extdesc-160$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Block-level image with empty alt and without role="presentation"$$, $$The test passes if assistive technology is able to detect that there is a graphic or image between the two lines of text.$$, 77, $$TODO XHTML$$, 12, 7, $$extdesc-170$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Inline graphic with empty alt and without role="presentation"$$, $$The test passes if assistive technology is able to detect that there is a graphic or image between the two sentences in the paragraph.$$, 78, $$TODO XHTML$$, 13, 7, $$extdesc-180$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Block-level image with role="presentation" and empty alt$$, $$The test passes if assistive technology is not able to detect the graphic or image between the following two lines of text.$$, 79, $$TODO XHTML$$, 14, 7, $$extdesc-190$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Inline graphic with role="presentation" and empty alt$$, $$The test passes if assistive technology is not able to detect the graphic or image in the middle of the paragraph.$$, 80, $$TODO XHTML$$, 15, 7, $$extdesc-200$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Expanding details and ease of reading$$, $$This test passes if all the following steps are successful:You can expand the details and the screen adjusts by itself, bringing the relevant text on screen.You can read to the end of description. After the recipe you should see some End of chapter Header and text to ensure nothing was cut off.Please repeat this test for paginated view as well as scroll view and provide a note about it. Please also include notes about usability of this approach.$$, 81, $$TODO XHTML$$, 16, 7, $$extdesc-210$$);
insert into epubtest."Tests"("name", "description", "id", "xhtml", "order", "test_book_id", "test_id") values ($$Collapsing and pagination$$, $$This test passes if the expanded description collapses without leaving space or pages behind. Two conditions must be satisfied:On activating the expand/collapse button twice, the description first expands then collapses.The extra pages or space created for showing the extended description also collapse, and you are able to read end of chapter header and text just after the expand/collapse button.Please repeat this test for paginated view as well as scrolling view, and provide a note about it. Please also include notes about usability of this approach.$$, 82, $$TODO XHTML$$, 17, 7, $$extdesc-220$$);
